config/routes.rb
InvestmentsJson::Application.routes.draw do

  root to: 'static#index'

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'about' => 'static#about'
  get 'specification' => 'static#specification'

  resources :investors, :only => [ :new, :create ] do
    collection do
      get   'load'       # form for existing investment.js file
      get   'crunchbase' # form for crunchbase data import
      get   'edit'       # editing imported
      post  'parse'      # parsing existing investment.js
      post  'import'     # importing crunchbase data
    end
  end

  resources :locations, :only => [ :index, :new, :create, :destroy ]

end

app/models/investor.rb
class Investor < ActiveRecord::Base

  has_many :companies

  validates :investor, :presence => true

  accepts_nested_attributes_for :companies, :allow_destroy => true
end

app/controllers/investors_controller.rb
require "net/http"
require "uri"

class InvestorsController < ApplicationController

  skip_before_filter :require_login

  def new

    @investor = Investor.new
    @company = @investor.companies.new
    @company.rounds.new
    @company.events.new
    @partial = 'investors/new'

  end # new

  def create

    @partial = 'investors/new'

    investor_params = params.require(:investor).permit(
      :investor,
      :url,
      {:companies_attributes =>
        [:name, :url, :_destroy,
          {:rounds_attributes => [:name, :date, :_destroy]},
          {:events_attributes => [:name, :date, :_destroy]}
        ]
      }
    )

    @investor = Investor.new(investor_params)

    if @investor.valid?

      @investor.version = '1.0.0'
      @investor.updated = Time.now

      @companies = @investor.companies.reject { |company| company.name.blank? }
      @companies.each do |company|
        company.rounds = company.rounds.reject { |round| round.name.blank? }
        company.events = company.events.reject { |event| event.name.blank? }
      end

      if @companies.length == 0
        flash.now[:error] = "You'll have to give us a little information about your investments for this to work." # change?
        render 'new'
      end

    else # validation errors
      flash.now[:error] = "Whoops. Please correct the highlighted errors first."
      render 'new'
    end

  end # create

  def load
  end

  def parse

    if params[:investment][:url].blank?
      render 'load'
    else

      json_object = json_file_pull(params[:investment][:url])

      if json_object.nil?
        flash.now[:error] = "That didn't work - either the URL was wrong or the content wasn't valid."
        render 'load'
      else
        @investor = create_investor(json_object)
        unless @investor.companies.any?
          flash[:error] = "We're sorry - we couldn't retrieve any data from that file."
        end
        @partial = 'investors/edit'
        render 'new'
      end

    end

  end # parse


  def crunchbase
  end

  def import

    if params[:investment][:url].blank?
      flash.now[:error] = "You'll have to enter a Crunchbase URL."
      render 'crunchbase'
    end

    uri = URI::parse(params[:investment][:url])

    if (params[:investment][:url] =~ URI::regexp('http')).nil?

      flash.now[:error] = "We're sorry, but that wasn't a valid URL."
      render 'crunchbase'

    elsif !uri.host or !uri.host.include? "crunchbase.com"

      flash.now[:error] = "We're sorry, but that wasn't a valid Crunchbase URL."
      render 'crunchbase'

    else

      @investor = crunchbase_api(uri.path)

      if @investor.companies.any?
        @partial = 'investors/import'
        render 'new'
      else
        @partial = 'investors/new'
        flash.now[:error] = "We're sorry - we couldn't retrieve any investment information from that Crunchbase page."
        render 'new'
      end

    end

  end

  protected

  # ghetto error handling - if it's nil something went wrong and I don't much care what
  def json_file_pull(url)
    begin
      JSON.parse HTTParty.get(url).response.body
    rescue
      nil
    end
  end # json_file_pull

  # takes the json object and makes an investor out of it
  def create_investor(json_object)

    if json_object.include?("name") && json_object["name"] == "investments.js" && json_object.include?("version") && json_object["version"] == "1.0.0"
      format_1_0_0(json_object)
    else
      format_0(json_object)
    end

  end # create_investor

  # for dealing with Jerry's original file format without API version
  def format_0(json_object)

    investor = Investor.new

    companies = json_object.reject { |item| !item.include?("company") }

    companies.map { |data|
      company = investor.companies.new(:name => data["company"], :url => data["url"])
      data["rounds"].map { |round| company.rounds.new(:name => round["Series"], :date => Date.strptime(round["date"], "%m/%Y")) } if data["rounds"]
      data["events"].map { |event| company.events.new(:name => event["event"], :date => Date.strptime(event["date"], "%m/%Y")) } if data["events"]
    }

    investor

  end

  # for the 1.0.0 specification.
  def format_1_0_0(json_object)

    investor = Investor.new
    investor.investor = json_object["investor"]
    investor.url = json_object["url"] if json_object["url"]

    companies = json_object["investments"].reject { |item| !item.include?("company") }

    companies.map { |data|
      company = investor.companies.new(:name => data["company"], :url => data["url"])
      data["rounds"].map { |round| company.rounds.new(:name => round["series"], :date => Date.strptime(round["date"], "%m/%Y")) } if data["rounds"]
      data["events"].map { |event| company.events.new(:name => event["event"], :date => Date.strptime(event["date"], "%m/%Y")) } if data["events"]
    }

    investor

  end

  def crunchbase_api(path)

    api_base = 'http://api.crunchbase.com/v/1/'
    api_key = ENV['CRUNCHBASE_API_KEY']

    crunchbase_url = api_base+path+".js?api_key="+api_key

    investor = Investor.new

    begin

      response = JSON.parse HTTParty.get(crunchbase_url).response.body

      if response["name"]
        investor.investor = response["name"].strip
      elsif response["first_name"] and response["last_name"]
        investor.investor = response["first_name"].strip+' '+response["last_name"].strip
      end

      investor.url = response["homepage_url"]

      if response["investments"]

        companies = Hash.new { |h,k| h[k] = [] }

        response["investments"].map do |data|

          investment = data["funding_round"]

          companies[investment["company"]["name"]] << {
            name:       investment["round_code"].strip.capitalize,
            date:       Date.strptime("#{investment["funded_month"]}/#{investment["funded_year"]}", "%m/%Y"),
            permalink:  investment["company"]["permalink"].strip
          }

        end

        companies.each do |data|

          # need to fetch the damn company URLs from the company pages because they're not in the investor API call
          crunchbase_company_url = "#{api_base}company/"+data[1][0][:permalink]+".js?api_key=#{api_key}"

          begin
            company_response = JSON.parse HTTParty.get(crunchbase_company_url).response.body
            company_url = company_response["homepage_url"].strip
          rescue JSON::ParserError # timeouts, just skip fetching the url
          end

          company = investor.companies.new(:name => data[0], :url => company_url)
          # company = investor.companies.new(:name => data[0])

          data[1].map { |round| company.rounds.new(:name => round[:name], :date => round[:date]) }

        end

      end
    rescue
    end

    investor

  end

end

app/views/investors/_edit.html.erb
<h3>Edit your Investments.js file</h3>
<p>Here's what we found in your Investments.js file.</p>
<p>You can edit your existing set of investments or add new ones to the list.</p>
<p>Please complete your editing before re-creating your Investments.js file. There's no save halfway-through.</p>

app/views/investors/_import.html.erb
<h3>Edit your Investments.js file</h3>
<p>Here's what we managed to import from Crunchbase. Please look over it for accuracy.</p>
<p>You can edit your existing set of investments or add new ones to the list.</p>
<p>Please complete your editing before creating your file Investments.js file. There's no save halfway-through.</p>

app/views/investors/_new.html.erb
<h3>Create a new Investments.js file</h3>
<p>For each investment, you'll require the company's name &amp; website, the series you invested in, and the month you invested.</p>
<p>You can also add significant corporate events, like exits. These are completely optional.</p>
<p>If you've got information about your firm on <%= link_to "Crunchbase", "http://www.crunchbase.com" %>, get a head-start by <%= link_to "importing your data", crunchbase_investors_path %>.
<p>Please enter all your investments before creating your Investments.js file. There's no save halfway-through.</p>

app/views/investors/create.html.erb
<h3>Your Investments.js file is ready!</h3>
<p>Copy the below JSON exactly as it appears, before you leave this page. We don't save your file after you leave, and we'd hate to have you enter all that information again.</p>
<p>Note that you are still responsible for saving and uploading your Investments.js file to a publicly-accessible place.</p>
<h3>Investments.js:</h3>
<div class="well">
<%= render :partial => 'investors/create.json.jbuilder' %>
</div>

app/views/investors/crunchbase.html.erb
<h3>Import information from Crunchbase</h3>
<p>Get a headstart on your Investments.js file by importing data from Crunchbase. Just paste the URL of your page below.</p>
<p>Be patient - importing from Crunchbase can take some time.</p>
<%= simple_form_for :investment, :url => '/investors/import', :html => { :class => 'form-horizontal' } do |investment| %>
  <div class="well">
    <%= investment.input :url, :as => :string, :label => "Crunchbase URL", :hint => "e.g. 'http://www.crunchbase.com/financial-organization/neu-venture-capital'", :input_html => { :class => "span5" } %>
  </div>
  <%= investment.button :submit, "Import my Crunchbase data", :class => 'btn btn-primary btn-large' %>
<% end %>

app/views/investors/load.html.erb
<h3>Load an existing Investments.js file</h3>
<p>Enter the URL of a publicly-available Investments.js file below, and we'll load it for editing.</p>
<%= simple_form_for :investment, :url => '/investors/parse', :html => { :class => 'form-horizontal' } do |investment| %>
  <div class="well">
    <%= investment.input :url, :as => :string, :label => "Investments.js URL", :hint => "Please make sure to enter a complete URL!", :input_html => { :class => "span5" } %>
  </div>
  <%= investment.button :submit, "Fetch my Investments.js file", :class => 'btn btn-primary btn-large' %>
<% end %>

app/views/investors/new.html.erb
<%= render :partial => @partial %>
<%= simple_nested_form_for @investor, :html => { :class => 'form-horizontal' } do |investor| %>
  <h3>Your Information</h3>
    <div class="well">
      <%= investor.input :investor, :label => "Investor Name", :hint => "Enter your name or the name of your firm", :input_html => { :class => "span5"} %>
      <%= investor.input :url, :label => "Your Website", :hint => "Provide a URL for your website", :input_html => { :class => "span5"} %>
    </div>
  <h3>Your Investments</h3>
    <%= investor.fields_for :companies do |company| %>
      <div class="well">
        <%= company.input :name, :label => "Investment Name", :hint => "Enter the name of the company here", :input_html => { :class => "span5"} %>
        <%= company.link_to_remove "Remove this investment", :class => 'btn btn-danger btn-remove', :wrapper_html => { :class => "flush" } %>
        <%= company.input :url, :label => "Website Address", :hint => "Enter the URL of the company here", :input_html => { :class => "span5"} %>
        <%= company.fields_for :rounds do |round| %>
          <%= round.input :name, :label => "Round", :hint => "Seed, Series A, Series B...", :input_html => { :class => "span3" } %>
          <%= round.input :date, :label => false, :hint => "Date of Investment", start_year: Date.today.year + 1, end_year: Date.today.year - 20, discard_day: true, order: [:month, :year], :input_html => { :class => "datewidth"}, :wrapper_html => { :class => "flush" } %>
          <%= round.link_to_remove "Remove this round", :class => 'btn btn-danger btn-remove' %>
        <% end %>
        <p><%= company.link_to_add "Add another round", :rounds, :class => 'btn btn-primary btn-add' %></p>
        <hr />
        <%= company.fields_for :events do |event| %>
          <%= event.input :name, :label => "Event", :hint => "Acquisition, IPO, etc.", :input_html => { :class => "span3" }  %>
          <%= event.input :date, :label => false, :hint => "Date of Event", start_year: Date.today.year + 1, end_year: Date.today.year - 20, discard_day: true, order: [:month, :year], :input_html => { :class => "datewidth"}, :wrapper_html => { :class => "flush" } %>
          <%= event.link_to_remove "Remove this event", :class => 'btn btn-danger btn-remove' %>
        <% end %>
        <p><%= company.link_to_add "Add another event", :events, :class => 'btn btn-primary btn-add' %></p>
      </div>
  <% end %>
  <p><%= investor.link_to_add "Add another investment", :companies, :class => 'btn btn-primary btn-large' %>
  <%= investor.button :submit, "I'm done - create my Investments.js file!", :class => 'btn btn-primary btn-large pull-right' %></p>
<% end %>

app/views/investors/parse.html.erb
<div class="well">
<p><%= @json_object.inspect %></p>
</div>