config/routes.rb
InvestmentsJson::Application.routes.draw do

  root to: 'static#index'

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'about' => 'static#about'
  get 'specification' => 'static#specification'

  resources :investors, :only => [ :new, :create ] do
    collection do
      get   'load'       # form for existing investment.js file
      get   'crunchbase' # form for crunchbase data import
      get   'edit'       # editing imported
      post  'parse'      # parsing existing investment.js
      post  'import'     # importing crunchbase data
    end
  end

  resources :locations, :only => [ :index, :new, :create, :destroy ]

end

app/models/location.rb
class Location < ActiveRecord::Base

  validates :name, :url, :presence => true

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  skip_before_filter :require_login, :only => [:index]

  before_filter :require_admin, :except => [:index]

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create

    location_params = params.require(:location).permit(
      :name,
      :url
    )

    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_url, :notice => "Great, we've added that location."
    else
      render :new
    end

  end

  def destroy

    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_url

  end

end

app/views/locations/index.html.erb
<h3>Locations of Investment.js files</h3>
<p>Looking for investment.js data? Here's some places to start.</p>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th><th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to location.url, location.url %></td>
        <td>
          <%= link_to_if(admin?, 'Delete', location_path(location.id), :confirm => "Are you sure?", :method => :delete){} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to_if(admin?, 'Add a location', new_location_path, :class => "btn btn-primary btn-large"){} %>

app/views/locations/new.html.erb
<h3>Create a new investments.js location</h3>
<%= simple_form_for @location, :html => {:class => 'form-horizontal' } do |location| %>
  <div class="well">
    <%= location.input :name, :hint => "The name of the person or institution", :input_html => { :class => "span5" } %>
    <%= location.input :url, :hint => "The location of the investments.js file", :input_html => { :class => "span5" } %>
  </div>
  <%= location.button :submit, "Add this location", :class => 'btn btn-primary btn-large' %>
<% end %>