config/routes.rb
InvestmentsJson::Application.routes.draw do

  root to: 'static#index'

  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'about' => 'static#about'
  get 'specification' => 'static#specification'

  resources :investors, :only => [ :new, :create ] do
    collection do
      get   'load'       # form for existing investment.js file
      get   'crunchbase' # form for crunchbase data import
      get   'edit'       # editing imported
      post  'parse'      # parsing existing investment.js
      post  'import'     # importing crunchbase data
    end
  end

  resources :locations, :only => [ :index, :new, :create, :destroy ]

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
  <nav class="navbar-inner">
    <div class="container">
      <p class="navbar-text pull-left"><%= link_to "VCDelta.org coded by Greg Yardley.", about_path %></p>
      <ul class="nav pull-right">
        <li><%= link_to "View source on GitHub", "https://github.com/gyardley/vcdelta" %></li>
      </ul>
    </div>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "VCDelta.org", root_path, :class => 'brand' %>
<ul class="nav pull-right">
  <% if logged_in? %>
    <li>
      <p class="navbar-text visible-desktop"><%= current_user.email %></p>
    </li>
    <li>
      <p class="navbar-text"><%= link_to "Logout", logout_path %></p>
    </li>
  <% else %>
    <li>
      <p class="navbar-text visible-desktop">A simple generator for machine-readable VC investment data.</p>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="tinfoil-site-verification" content="42fec5fba91a650632794bc19cbe1f72e2c08490" />
    <title><%= content_for?(:title) ? yield(:title) : "VCDelta" %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main" class="container">
      <div class="content">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>